
```yaml
project:
  seed: 42
  timezone: "UTC"

data:
  base_dir: "data"
  raw_dir: "data/raw"
  bronze_dir: "data/bronze"
  silver_dir: "data/silver"
  gold_dir: "data/gold"
  services: 50
  days: 30
  freq: "1min"
  env: "prod"

labels:
  incident_latency_p95_ms: 1200
  incident_error_rate: 0.05
  incident_min_duration_min: 5
  prediction_horizon_min: 15

splits:
  train_days: [1, 21]
  val_days: [22, 26]
  test_days: [27, 30]

features:
  windows_min: [1, 5, 15, 30, 60]
  stats: ["mean", "std", "p95", "slope", "delta"]

model:
  type: "xgboost"
  params:
    n_estimators: 400
    max_depth: 6
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    reg_lambda: 1.0
  class_weight: "balanced"

alerting:
  max_alerts_per_day: 5
  cooldown_min: 30
  consecutive_hits_required: 2
  precision_target: 0.80
  recall_target: 0.60

drift:
  data_drift_method: "psi"     # psi or ks
  psi_warn: 0.1
  psi_alert: 0.25
  concept_drift_window_min: 1440  # 1 day window
  health_drop_warn: 0.05
  health_drop_alert: 0.10

